const ErrorCodes = {
  PASSPORT_UNAUTHORIZED_ERROR_CODE: 1,
  INVALID_CREDENTIALS_ERROR_CODE: 2,
  ACCOUNT_LOCKED_ERROR_CODE: 3,
  INVALID_NEW_PASSWORD_ERROR_CODE: 4,
  USER_NOT_FOUND_ERROR_CODE: 5,
  EMPLOYEE_NOT_FOUND_ERROR_CODE: 6,
  DUPLICATED_USER_ERROR_CODE: 7,
  CUSTOMER_NOT_FOUND_ERROR_CODE: 8,
  TRANSACTION_NOT_FOUND_ERROR_CODE: 9,
  ITEM_NOT_FOUND_ERROR_CODE: 10,
  DUPLICATED_PASSPORT_NUMBER_ERROR_CODE: 11,
  STOCK_NOT_FOUND_ERROR_CODE: 12,
  PURCHASE_NOT_FOUND_ERROR_CODE: 13,
  PAYROLL_NOT_FOUND_ERROR_CODE: 15,
  COMMISSION_NOT_FOUND_ERROR_CODE: 16,
  IMAGE_NOT_FOUND_ERROR_CODE: 14,
  INSUFFICIENT_PERMISSION_ERROR_CODE: 66,
  INPUT_VALIDATION_ERROR_CODE: 77,
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99
};

export default ErrorCodes;
